### PR TITLE
Add SUFFIXCOMMAND with -no-cef-sandbox passed by default

### PR DESCRIPTION
**Pull request by terencode**
This workaround https://bugs.winehq.org/show_bug.cgi?id=39403

### CODE REVIEW

**Comment by nefelim4ag** [comment]
Ok, tested.

**Comment by terencode** [comment]
Thanks @Nefelim4ag.
Also, why do you check for additional drives and delete them on startup?

**Comment by nefelim4ag** [comment]
@terencode,
Just forced type of sandbox'ing, i hate when wine add files to somewhere else/or have access.

**Comment by terencode** [comment]
I agree with that but what about sharing the same files from your windows
system drive?

**Comment by nefelim4ag** [comment]
You can just create a symlink to wine prefix, ex, dir in prefix -> mount point
Or just mount drive in prefix, or make a bind mount...
i.e. that not a problem.

**Comment by terencode** [comment]
I tried and it didn't work. Steam redownloads the game.
Have you tried it?

**Comment by nefelim4ag** [comment]
I'm don't use windows for several years, so i don't have a ntfs disk with games.
You must check why it redownload files:
 - Time stamps differ.
 - Steam don't see him
 - Steam just download different language
& etc.

And that's only on your own, i.e. i can't help.

**Comment by terencode** [comment]
Fine, my point was just that it's not necessary good to force this 'sandbox' and instead would be better to allow the user to disable it if necessary...

**Comment by nefelim4ag** [comment]
@terencode , if i understood you correctly:
https://github.com/Nefelim4ag/steam-wine/commit/dd2238b45b454168539cebc4f3484f72a117fa4a

**Comment by terencode** [comment]
I think you did ^^ thanks for those quick updates!

**Pull request merged**
